// shared/components/BackButton/BackButton.tsx
import { FC } from 'react';
import IconBack from '@public/assets/icons/arrow-left-12.svg';
import router from 'next/router';
import { Button } from '../Button/Button';

export const BackButton: FC = ({}) => {
  function handleClick() {
    router.back();
  }

  return (
    <Button style="outline" size="small" onClick={handleClick}>
      <IconBack /> Back
    </Button>
  );
};

// shared/components/BackButton/BackButton.svelte
<script>
  import { browser } from '$app/env';

  import IconBack from 'icons/arrow-left-12.svg';
  import Button from 'components/Button/Button.svelte';

  const handleClick = () => {
    if (!browser) {
      return;
    }
    history.back();
  };
</script>

{#if browser && Boolean(window.history.length)}
  <Button
    style="outline"
    size="small"
    title="Go back"
    on:click={handleClick}
    {...$$restProps}
  >
    <slot><IconBack /> Back</slot>
  </Button>
{/if}
